/// Annotated classes.
class IDKitImageNote {
  // File path of image resources.
  final String filePath;
  // The name of the class generated by the annotation.
  final String className;
  // Build class.
  const IDKitImageNote(this.filePath, this.className)
      : assert(filePath != null, "fileParh cannot be null!"),
        assert(className != null, "className cannot be null!");
}
